<div class="ic"></div>
             <div class="iconHolder">
         <div id="img_slider">
            <ul>
                <li>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/galleryIcon1.jpg"><span class="zoomSp"></span><img src="images/small-galleryIcon1.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon2.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon3.jpg" alt=""></a></div>
                </li>
                <li>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon4.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon5.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon6.jpg" alt=""></a></div>
                </li>
                <li>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon7.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon8.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon9.jpg" alt=""></a></div>
                </li>
                <li>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon7.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon8.jpg" alt=""></a></div>
                    <div class="picHold"><a class="pic" rel="Appendix" href="images/image-blank.png"><span class="zoomSp"></span><img src="images/galleryIcon9.jpg" alt=""></a></div>
                </li>
            </ul>
            
        </div>
            <a href="#" id="next"><img src="images/gallNext1.png" alt=""></a>
            <a href="#" id="prev"><img src="images/gallPrev1.png" alt=""></a>
    </div>
				<ul>
					
                     <li id="pageAbout">
					   <div class="box">
                            <div class="closePlane">
                                <a class="closeButton" href="#!/pageGallery"><img src="images/closeIcon.png" alt=""></a>
                            </div>
                            <div class="containerContent">
                                
                                <h2>Welcome to Our Studio!</h2>
                                <div class="col1 padBot1">
                                <div class="Btns2">
                                        <a href="#" class="upBtn"></a>
                                        <a href="#" class="downBtn"></a>
                                    </div>
                                    
                                    <div class="scroll2">
                                    <figure class="_fig1">
                                        <img src="images/page1pic1.png" alt="" width="584px">
                                    </figure>
                                    <div>
                                        <p>Cream is one of <a class="_link1" href="http://blog.templatemonster.com/category/free-website-templates/">free website templates</a> created by TemplateMonster.com team. This website template is optimized for 1280X1024 screen resolution. It is also XHTML &amp; CSS valid. The PSD source files of this <a class="_link1" href="http://blog.templatemonster.com/2012/05/07/free-full-javascript-animated-template-web-design-studio/">Cream Template</a> are available for free for the registered members of TemplateMonster.com. Feel free to get them!</p>
                                    </div>
                               
                                
                                    <!--<div class="col3 bord1 magRight1">
                                        <ul class="_list1">
                                            <li><a href="#">At vero eos et accusam justo</a></li>
                                            <li><a href="#">Stet clitasd gubergren nosea takimata</a></li>
                                            <li><a href="#">Duo dolores et sed diam rebum</a></li>
                                        </ul>
                                    </div>  -->                 
                                </div>
                            </div>
                       </div>	
					</li>
					<li id="pageServices">
                    	 <div class="box">
                                <div class="closePlane">
                                    <a class="closeButton" href="#!/pageGallery"><img src="images/closeIcon.png" alt=""></a>
                             </div>
                            <div class="containerContent">
                            	<h2>Nos Services</h2>
                            	
                                <div class="col1">
                                    <div class="Btns2">
                                        <a href="#" class="upBtn"></a>
                                        <a href="#" class="downBtn"></a>
                                    </div>
                                    
                                    <div class="scroll2">
                                    	<div class="col1">
                                   		   <p style="text-align: justify;"> Aptes à œuvrer dans divers secteurs d'affaires : Publicité, Communication, technologies et services, DORA TELECOM se propose pour vous accompagner à partir de la conception et la création de votre image jusqu'à la livraison du matériel de communication de haute qualité. Tout est pensé, conçu et livré selon vos attentes et vos besoins.</p>
                                   		</div>
	                                    <div class="col1">
		                                    <div class="col8 magRight2">
		                                        <h3>Design Graphique</h3>
		                                        <div class="marge-left" >
		                                        	<h5>Création graphique et direction artistique</h5>
													<p>Par des maquettes, des illustrations, nous déployons des trésors d'idées pour élaborer une communication visuelle unique.</p>
													<h5>Infographie et prépresse</h5>
													<p>Une équipe imprégnée de talent réalise les visuels pour les documents appropriés et les prépare pour l'impression.</p>
													<h5>Gestion des étapes d'impression</h5>
													<p>Suivi et contrôle de qualité auprès des imprimeurs afin que les pièces imprimées soient en parfaite harmonie avec l'idée de départ.</p>
										        </div>
										        
		                                    </div>
		                                    
		                                    <div class="col8 magRight2">
		                                        <h3>Stratégie & Conseil</h3>
		                                        <div class="marge-left" >
		                                        	<p>Vous pouvez compter sur une équipe extrêmement professionnelle et entièrement dévouée au succès de vos projets de communication et de marketing. Toutes nos actions s'inscrivent dans une stratégie globale visant l'atteinte des objectifs d'affaires de chacun de nos clients.</p>
										        </div>
		                                    </div>
		                                </div>
                                    </div>
                                </div> 
                            </div>
                       </div>
                    </li>
                     
                   <li id="pageGallery">
                    </li>
                    
                    <li id="pagePrivacy">
                    	   <div class="box">
                                <div class="closePlane">
                                    <a class="closeButton" href="#!/pageGallery"><img src="images/closeIcon.png" alt=""></a>
                             </div>
                            <div class="containerContent">
                            <h2>Privacy Policy</h2>
                                <div class="col1">
                                    <div class="Btns1">
                                        <a href="#" class="upBtn"></a>
                                        <a href="#" class="downBtn"></a>
                                    </div>
                                    <div class="scroll1">
                                       
                                        <p class="padBot4">Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                                        <p class="padBot4">At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus. Duis autem vel eum iriure dolor in hendrerit.</p>
                                        <p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                                    </div>
                                </div> 
                            </div>
                       </div>
                    </li>
                    
                    <li id="pageContact">
					   <div class="box">
                         <div class="closePlane">
                                <a class="closeButton" href="#!/pageGallery"><img src="images/closeIcon.png" alt=""></a>
                            </div>
                            
                          <div class="containerContent">
                            <div class="col5 magRight3">
                            <h2>feedback</h2>
                                <div class="wrapper">
                                        <form action="#" id="ContactForm">	
                                        <div class="success"> Contact form submitted!&nbsp;We will be in touch soon.</div>	
       								 		<fieldset class="left">	
                                                        <div class="block">
                                                        <label class="name padRight3">
                                                            <span class="title1">Nom:</span>
                                                            <span class="bg"><input type="text" value="" class="input"></span>
                                                            <span class="error">*This is not a valid name.</span> <span class="empty">*This field is required.</span> </label>
        											     <label class="email">
                                                            <span class="title1">Email:</span>
            											    <span class="bg"><input type="email" value="" class="input"></span>
            											    <span class="error">*This is not a valid email address.</span> <span class="empty">*This field is required.</span></label>   
                                                         
                                                         <label class="phone">
                                                         <span class="title1">Tel:</span>
                                                            <span class="bg"><input type="tel" value="" class="input"></span>
                                                            <span class="error">*This is not a valid number.</span> <span class="empty">*This field is required.</span> </label>
                                                         </div>
                                                         
                                                         <div class="block">
                                                         <label class="message">
                                                         <span class="title1">Message:</span>
            											    <span class="bg"><textarea rows="1" cols="2"></textarea></span>
            											    <span class="error">*The message is too short.</span> <span class="empty">*This field is required.</span> </label>
        										         </div>
                                                         <div class="formButtons">
                                                          <div class="formBtn">
                                                                <a href="#" data-type="submit" class="moreButton">Envoyer</a>
                                                          </div>
                                                          <div class="formBtn">
                                                                 <a href="#" data-type="reset" class="moreButton">Vider</a>
                                                          </div>
                                                         </div> 
    								  		    </fieldset>
                                            </form>
                                    </div>
                            </div>  
                            <div class="col5">
                                <h2>Contact</h2>
                                <div class="padBot5">
                                	
                                    <figure class="google__map">
                                    	<div data-lng="-5.578418" data-lat="33.885903" class="map" style="height: 200px; width: 100%;" ></div>
                                    </figure> 
                                </div>
                               <div class="col5">
                                    <p>
                                        <span>522 Diour Salam 4ème Tranche,<br>Hay AL AMANE.</span><br>
                                        <span class="space1">Tél/Fax:</span>0535-53-70-90<br>
                                        <span class="space1">GSM:</span>0661-13-88-14<br>
                                        <span>E-mail:&nbsp;<a class="_link1" href="mailto:">dora.telecom@gmail.com</a></span>    
                                    </p>
                               </div>
                            </div>     
                        </div>
                       </div>	
					</li>
                  
                	<li id="pageMore">
                    	 <div class="box">
                                <div class="closePlane">
                                    <a class="closeButton" href="#!/pageGallery"><img src="images/closeIcon.png" alt=""></a>
                             </div>
                            <div class="containerContent">
                            <h2>Lorem Ipsum</h2>
                                <div class="col1">
                                    <div class="Btns2">
                                        <a href="#" class="upBtn"></a>
                                        <a href="#" class="downBtn"></a>
                                    </div>
                                    <div class="scroll2">
                                       
                                        <p class="padBot4">Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                                        <p class="padBot4">At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus. Duis autem vel eum iriure dolor in hendrerit.</p>
                                        <p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                                    </div>
                                </div> 
                            </div>
                       </div>
                    </li>
				</ul>