<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="iso-8">
  <link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
  <link rel="stylesheet" href="css/layout.css" type="text/css" media="all">
  <link rel="stylesheet" href="css/style.css" type="text/css" media="all">
  <link rel="stylesheet" href="css/jquery.fancybox-1.3.4.css" type="text/css" media="all">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600,300' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="js/jquery-1.7.1.js" ></script>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
  <script type="text/javascript" src="js/scripts.js"></script>
  <link rel="shortcut icon" href="images/favicon.jpg">
  <!--[if lt IE 9]>
  	<script type="text/javascript" src="js/html5.js"></script>
    <link rel="stylesheet" href="css/ie.css" type="text/css" media="all">
    
  <![endif]-->
	<!--[if lt IE 8]>
		<div style=' clear: both; text-align:center; position: relative;'>
			<a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a>
		</div>
	<![endif]-->
</head>
<body>
<div class="glob">
<div class="page_spinner"></div>  
<div class="main">
    <div class="center"> 
   <!--header -->                   
 <div class="headerHolder">
       <header>
       <div class="logoHolder">
			<a href="<?= $_SERVER['PHP_SELF'] ?>" ><img src="images/logo.png" width="350px" /></a>
            <!-- <h1><a href="#!/pageGallery" id="logo">oratorio</a></h1>  -->
       </div>
        </header>
        <div class="followHolder">
                       <span><span style="color: #009de0; display: inline; " >(+212)</span> 535-53-70-90</span>
                       <span style="margin-top: 4px; color: rgb(255, 108, 0); ">dora.telecom@gmail.com</span>
                       <!-- <a href="#" class="myButton">Rejoignez nous sur FACEBOOK</a>-->
                            <!--<ul>
                                <li><a href="#"><img src="images/followIcon1.png" alt=""></a></li>
                                <li><a href="#"><img src="images/followIcon2.png" alt=""></a></li>
                                <li><a href="#"><img src="images/followIcon3.png" alt=""></a></li>
                        
                            </ul>  -->
                        </div>
 </div>
<!--header end--> 
    
            <div class="menuHolder">
            <nav class="menu">
				    	<ul id="menu"> 
					       	
                            <li class="with_ul"><a href="#!/pageAbout"><span class="overPlane"></span><span class="mText">à propos</span></a>
                                   
                                    <!--  <ul class="submenu_1">
                                	   <li><a href="#!/pageMore">Bienvenue</a></li>
                                	   <li><a href="#!/pageMore">studio</a></li>
                                	</ul>-->

                            </li>
                                <li><a href="#!/pageServices"><span class="overPlane"></span><span class="mText">services</span></a></li>
                             <li><a href="#!/pageGallery"><span class="overPlane"></span><span class="mText">portfolio</span></a></li>
                             <li><a href="#!/pagePrivacy"><span class="overPlane"></span><span class="mText">Clients</span></a></li>
                             <li><a href="#!/pageContact"><span class="overPlane"></span><span class="mText">contact</span></a></li>
					   </ul>
					   
				    </nav>
				    <div class="facebookOuter">
						 <div class="facebookInner">
							  <div class="fb-like-box" 
							      data-width="200" data-height="280" 
							      data-href="https://www.facebook.com/profile.php?id=665045936874599&fref=ts" 
							      data-show-faces="true" 
							      data-stream="false" data-header="true">
							  </div>          
						 </div>
					</div>
						           
					<div id="fb-root"></div>
					
					<script>(function(d, s, id) {
					  var js, fjs = d.getElementsByTagName(s)[0];
					  if (d.getElementById(id)) return;
					  js = d.createElement(s); js.id = id;
					  js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1";
					  fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));
					</script>
					
					
			</div>
			<!--content -->
			<article id="content">
				<?php echo $this->layout()->content; ?> 
			</article>
			<!--content end-->
                  <!--footer -->
            <footer>
				<!-- {%FOOTER_LINK} -->
                <div class="mainFooter" >
                <div class="privHold">
                     <pre class="textPrivacy">copyright © Dora Telecom - 2014 by <a href="http://www.devma.net" target="_blank">Devma</a>.</pre>
                 </div>
                 </div>
			</footer>
           	<!--footer end-->
            </div>
		</div>
</div>

<div style="position: fixed; width: 100%; height: 100%; top: 0; left:0; " >
	<video src="videoBack.mp4" width="100%" autoplay loop autobuffer preload="auto"  ></video>
</div>
	
<script>
$(window).load(function() {	
	$('.page_spinner').fadeOut();
	$('body').css({overflow:'auto', 'min-height':'800px'})
})
</script>
</body>
</html>